### ISSUE TITLE
alarm is not working

### ISSUE THREAD

**Issue by scarejar** [mehdidc/pomodoro#19]
Distro: Arch Linux
Yes mpg123 is installed.
Are there any logs I can send in?

**Comment by mehdidc** [comment]
Thanks for reporting this issue, could you please locate where clock.mp3 is ? unfortunately when mpg123 fails it passes silently the error I should probably change that, but probably it did not find the file.

**Comment by mehdidc** [comment]
I just figured out the reason thanks a lot for reporting, it's fixed, it should work now could you please  try with the new version ?
Thanks

**Comment by scarejar** [comment]
It's working now. Thanks for the app!
