### ISSUE TITLE
Print out time left

### ISSUE THREAD

**Issue by dmigo** [mehdidc/pomodoro#21]
This one is a feature proposal.

The current behavior:
```bash
➜  ~ pomodoro 25 5
Work now
```
The desired behavior:
```bash
➜  ~ pomodoro 25 5
Work now. Time left: 24:55 
```
The counter on the end keeps ticking, so that user would know how much time is left.

**Comment by mehdidc** [comment]
Thanks, this feature was implemented by @coup321: #22
