### ISSUE TITLE
Clize issue with python 2

### ISSUE THREAD

**Issue by mehdidc** [mehdidc/pomodoro#7]
@daiwai, do you still have this issue with python 2 ? Thanks

`Traceback (most recent call last): File "/usr/local/bin/pomodoro", line 4, in <module> __import__('pkg_resources').run_script('pomodoro==0.1', 'pomodoro') File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script self.require(requires)[0].run_script(script_name, ns) File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script exec(code, namespace, namespace) File "/usr/local/lib/python2.7/dist-packages/pomodoro-0.1-py2.7.egg/EGG-INFO/scripts/pomodoro", line 4, in <module> from clize import run File "/usr/local/lib/python2.7/dist-packages/clize-4.0.2-py2.7.egg/clize/__init__.py", line 7, in <module> from clize.parser import Parameter File "/usr/local/lib/python2.7/dist-packages/clize-4.0.2-py2.7.egg/clize/parser.py", line 1057, in <module> class CliBoundArguments(object): File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 200, in attributes return wrap(maybe_cl) File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 184, in wrap _transform_attrs(cl, these) File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 137, in _transform_attrs .format(a=a) ValueError: No mandatory attributes allowed after an attribute with a default value or factory. Attribute in question: Attribute(name='posparam', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=False, convert=None)`

**Comment by daiwai** [comment]
@mehdidc, yes, with the current version it is now also working for me on Ubuntu with python 2.7.12. Thanks for the quick fix!

Just for reference, I also got it to work with the previous version by re-installing with Python 3, e.g.:  sudo python3 setup.py install

**Comment by mehdidc** [comment]
Ok, thank you @daiwai  ! Closing this issue.
